# Plugin Parameters
parameters:
    JiraHighEffortWidgetBundleConfig:
        widget_view: 'JiraHighEffortWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraHighEffortWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraHighEffortWidgetBundleService:
        class: RGies\JiraHighEffortWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraHighEffortWidgetBundleConfig%]
