# Plugin Parameters
parameters:
    JiraBurnDownWidgetBundleConfig:
        widget_view: 'JiraBurnDownWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraBurnDownWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraBurnDownWidgetBundleService:
        class: RGies\JiraBurnDownWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraBurnDownWidgetBundleConfig%]
