# General Parameters
parameters:
    platform_name: 'Agile Dashboard'
    platform_version: '1.1'

    # Widget update interval in minutes
    widget_update_interval: 5

    # Widget cache in minutes
    widget_cache:
        max_lifetime: 600
        default_lifetime: 10

    # Widget update interval
    update_intervals:
        300:    'Every 5 minutes (short)'
        600:    'Every 10 minutes (default)'
        900:    'Every 15 minutes'
        3600:   'Every 1 hour'
        14400:  'Every 4 hour'
        28800:  'Every 8 hour'

    # Widget icons
    widget_icons:
        'Default':    'ion ion-stats-bars'
        'No Icon':    ''
        'Bookmark':   'ion ion-android-bookmark'
        'Bug':        'ion ion-bug'
        'Cart':       'ion ion-android-cart'
        'Cloud':      'ion ion-cloud'
        'Code':       'ion ion-code-working'
        'Date':       'ion ion-android-calendar'
        'Experiment': 'ion ion-erlenmeyer-flask'
        'Eye':        'ion ion-eye'
        'Fire':       'ion ion-flame'
        'Folder':     'ion ion-folder'
        'Funnel':     'ion ion-funnel'
        'Global':     'ion ion-earth'
        'Happy':      'ion ion-happy-outline'
        'Heart':      'ion ion-heart'
        'Home':       'ion ion-android-home'
        'Inbox':      'ion ion-archive'
        'Magic':      'ion ion-wand'
        'Mail':       'ion ion-email'
        'Message':    'ion ion-chatboxes'
        'Money':      'fa fa-money'
        'Monitor':    'ion ion-monitor'
        'Package':    'ion ion-cube'
        'Radioactive': 'ion ion-nuclear'
        'Stop-watch': 'ion ion-android-stopwatch'
        'Speed':      'ion ion-speedometer'
        'Smartphone': 'ion ion-iphone'
        'Star':       'ion ion-android-star'
        'Search':     'ion ion-search'
        'Target':     'ion ion-pinpoint'
        'Tablet':     'ion ion-ipad'
        'Tag':        'ion ion-pricetag'
        'Time':       'ion ion-android-time'
        'Trend-down': 'ion ion-arrow-graph-down-right'
        'Trend-up':   'ion ion-arrow-graph-up-right'
        'Trophy':     'ion ion-trophy'
        'Unhappy':    'ion ion-sad-outline'
        'User':       'ion ion-person'
        'Warning':    'fa fa-warning'
