# General Parameters
parameters:
    platform_name: 'Agile Dashboard'
    platform_version: '1.0'

    # Widget plugins
    widget_plugins:
        'SampleWidgetBundle': 'Beispiel Widget'

    # Widget update intervall in minutes
    widget_update_interval: 5

    # Dashboard widgets
    widget_types:
        'jira/count': 'Jira Ticket Count'

    widget_icons:
        'Default': 'fa fa-bar-chart'


# Dashboard Services
services:
    widget_service:
        class:            RGies\MetricsBundle\Services\WidgetService
        arguments:        [@doctrine, %widget_types%, @service_container]


# Twig Configuration
twig:
    globals:
        # Variables

        # Services
        widgetService:  @widget_service
