jira_timeline_widget:
    resource: "@JiraTimelineWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

custom_timeline_widget:
    resource: "@CustomTimelineWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_burn_down_widget:
    resource: "@JiraBurnDownWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

custom_chart_widget:
    resource: "@CustomChartWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_performance_widget:
    resource: "@JiraPerformanceWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_history_widget:
    resource: "@JiraHistoryWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_core_widget:
    resource: "@JiraCoreWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_time_tracking_widget:
    resource: "@JiraTimeTrackingWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_high_effort_widget:
    resource: "@JiraHighEffortWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_list_widget:
    resource: "@JiraListWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_spendtime_widget:
    resource: "@JiraSpendTimeWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

separator_widget:
    resource: "@SeparatorWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

jira_count_widget:
    resource: "@JiraCountWidgetBundle/Controller/"
    type:     annotation
    prefix:   /

metrics:
    resource: "@MetricsBundle/Controller/"
    type:     annotation
    prefix:   /

