security:
    encoders:
        RGies\MetricsBundle\Entity\User:
            algorithm: sha256
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_USER:        [ROLE_VISITOR]
        ROLE_MANAGER:     [ROLE_VISITOR, ROLE_USER]
        ROLE_ADMIN:       [ROLE_VISITOR, ROLE_USER, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_VISITOR, ROLE_MANAGER, ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: MetricsBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt|gui)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: login
                check_path: login_auth
                success_handler: authentication_handler
                csrf_provider: form.csrf_provider
                csrf_parameter: _security_token
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /
            logout:
                path:   logout
                #target: _demo
            anonymous: ~

    access_control:
        - { path: ^/jira_core_widget_login, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_ADMIN }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/myprofile, roles: ROLE_USER }
        - { path: ^/(.*)_widget, roles: ROLE_VISITOR }
        - { path: ^/, roles: ROLE_VISITOR }
        #- { path: ^/[^login|^register], roles: ROLE_ADMIN }
