parameters:
    # Widget plugins
    widget_plugins:
        # General
        SeparatorWidgetBundle:      'Separator'

        # JIRA
        JiraBurnDownWidgetBundle:     'Jira - Sprint Burn Down'
        JiraCountWidgetBundle:        'Jira - Count issues'
        JiraSpendTimeWidgetBundle:    'Jira - Time spend on issues'
        JiraPerformanceWidgetBundle:  'Jira - Performance'
        JiraListWidgetBundle:         'Jira - List of selected issues'
        JiraHighEffortWidgetBundle:   'Jira - Highest efforts list'
        JiraTimeTrackingWidgetBundle: 'Jira - Time Tracking'
        JiraHistoryWidgetBundle:      'Jira - History Chart (Line, Bar Area)'
        JiraTimelineWidgetBundle:     'Jira - Roadmap by planed JIRA releases'
        JiraLeadTimeWidgetBundle:     'Jira - Lead time metric (Time to market)'
        JiraTimeInStateWidgetBundle:  'Jira - Time in state assessment'

        # Custom
        CustomChartWidgetBundle:      'Custom - Chart with manually entered data'
        CustomTimelineWidgetBundle:   'Custom - Timeline with manually entered data'
