# Plugin Parameters
parameters:
    JiraSpendTimeWidgetBundleConfig:
        widget_view: 'JiraSpendTimeWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraSpendTimeWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraSpendTimeWidgetBundleService:
        class: RGies\JiraSpendTimeWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraSpendTimeWidgetBundleConfig%]
