# Plugin Parameters
parameters:
    JiraLeadTimeWidgetBundleConfig:
        widget_view: 'JiraLeadTimeWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraLeadTimeWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraLeadTimeWidgetBundleService:
        class: RGies\JiraLeadTimeWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraLeadTimeWidgetBundleConfig%]
