# Plugin Parameters
parameters:
    JiraEstimatesWidgetBundleConfig:
        widget_view: 'JiraEstimatesWidgetBundle::default/widget.html.twig'
        edit_action: 'JiraEstimatesWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraEstimatesWidgetBundleService:
        class: RGies\JiraEstimatesWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraEstimatesWidgetBundleConfig%]
