# Plugin Parameters
parameters:
    JiraTimelineWidgetBundleConfig:
        widget_view: 'JiraTimelineWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraTimelineWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraTimelineWidgetBundleService:
        class: RGies\JiraTimelineWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraTimelineWidgetBundleConfig%]
