# Plugin Parameters
parameters:
    SeparatorWidgetBundleConfig:
        widget_view: 'SeparatorWidgetBundle::Default/widget.html.twig'
        edit_action: 'SeparatorWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    SeparatorWidgetBundleService:
        class: RGies\SeparatorWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %SeparatorWidgetBundleConfig%]
