# Plugin Parameters
parameters:
    JiraHistoryWidgetBundleConfig:
        widget_view: 'JiraHistoryWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraHistoryWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraHistoryWidgetBundleService:
        class: RGies\JiraHistoryWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraHistoryWidgetBundleConfig%]
