# Plugin Parameters
parameters:
    JiraCountWidgetBundleConfig:
        widget_view: 'JiraCountWidgetBundle::Default/widget.html.twig'
        edit_action: 'JiraCountWidgetBundle_widgetconfig_edit'

# Plugin Services
services:
    JiraCountWidgetBundleService:
        class: RGies\JiraCountWidgetBundle\Services\WidgetPluginService
        arguments: [@doctrine, %JiraCountWidgetBundleConfig%]
