# Plugin Parameters
parameters:
    JiraCoreWidgetBundleConfig:
        icon: 'bundles/jiracorewidget/images/jira.png'
        action: 'jira_core_widget_login_edit'

# Plugin Services
services:
    JiraCoreService:
        class: RGies\JiraCoreWidgetBundle\Services\JiraCoreService
        arguments: [@doctrine, @credential_service]
